version: 2

jobs:
  build:
    docker:
    - image: circleci/android:api-27
    - image: circleci/openjdk:8-jdk

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
        command: sudo chmod +x ./gradlew
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        paths:
        - ~/.gradle
    - run:
        name: Get all Git tags
        command: git fetch --tags
    - run:
        name: Spotless / KTLint
        command: ./gradlew spotlessCheck
    - run:
        name: Build Release
        command: ./gradlew assembleRelease -PdisablePreDex
    - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
        path: app/build/outputs/
        destination: artifacts